# Generated by Django 5.1.6 on 2025-02-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0003_book_favorite_alter_book_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='favorite',
            new_name='is_favorite',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='review_text',
        ),
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
