# Generated by Django 5.1.6 on 2025-02-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0006_rename_is_favorite_book_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('reading', 'Currently Reading'), ('completed', 'Completed'), ('want to read ', 'Want to Read')], default='wishlist', max_length=20),
        ),
    ]
